//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VisitСontrol.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkingDay
    {
        public int ID { get; set; }
        public int EmployeeID { get; set; }
        public System.DateTime ThisDay { get; set; }
        public System.TimeSpan FirstVisit { get; set; }
        public System.TimeSpan LeftForLunch { get; set; }
        public System.TimeSpan ReturnedFromLunch { get; set; }
        public System.TimeSpan LastLeaving { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
